config/routes.rb
Rails.application.routes.draw do
  get 'send/index'

  resources :voices
  resources :statuses
  resources :contests, param: :url
  get 'home/index'
  devise_for :users
  root 'home#index', as: 'home'
  get  '/contests',   to: 'contests#index'
  get  '/voice',  to: 'voices#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 end

app/models/contest.rb
class Contest < ApplicationRecord
	belongs_to :user
	has_attached_file :banner, :style => { :small => "150x150>", :large => '300x400' },
				  :url  => "http://vocesclouds3.s3.amazonaws.com/",
				  :path => "/public/assets/constests/:id/:style/:basename.:extension", 
				  validate_media_type: false

	
	validates_attachment_size :banner, :less_than => 5.megabytes
	validates_attachment_content_type :banner, :content_type => ['image/jpeg', 'image/png']

	validates :name,  presence: true
	validates :url,  presence: true
	validates :value,  presence: true
	validates :script,  presence: true
	validates :recomendations,  presence: true
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_action :set_contest, only: [:show, :edit, :update, :destroy]

  # GET /contests
  # GET /contests.json
  def index
    if current_user
      @contests = Contest.where(user_id: current_user).order(created_at: :desc)
    else
      @contests = Contest.all
    end
  end

  # GET /contests/1
  # GET /contests/1.json
  def show
    system "rake test CONTEST_ID=#{params[:id]}"
    @banner = "http://d2gnw0j9fh1sj8.cloudfront.net"+Contest.find_by(url: params[:url]).banner.url.split("vocesclouds3")[1]
    @voices = Voice.where(contest_id: Contest.find_by(url: params[:url]))
    .paginate(:page => params[:page], :per_page => 50)
  end

  # GET /contests/new
  def new
    @contest = Contest.new
  end

  # GET /contests/1/edit
  def edit
  end

  # POST /contests
  # POST /contests.json
  def create
    @contest = Contest.new(contest_params)
    @contest.user_id = current_user.id
    respond_to do |format|
      if @contest.save
        format.html { redirect_to '/contests/'+@contest.url, notice: 'Contest was successfully created.' }
        format.json { render :show, status: :created, location: @contest }
      else
        format.html { render :new }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contests/1
  # PATCH/PUT /contests/1.json
  def update
    @contest = Contest.find_by(url: params[:contest][:url])
    respond_to do |format|
      if @contest.update(contest_params)
        format.html { redirect_to '/contests/'+@contest.url, notice: 'Contest was successfully updated.' }
        format.json { render :show, status: :ok, location: @contest }
      else
        format.html { render :edit }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contests/1
  # DELETE /contests/1.json
  def destroy

    @contest.user_id = current_user.id

    @contest.destroy
    respond_to do |format|
      format.html { redirect_to contests_url, notice: 'Contest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contest
      @contest = Contest.find_by(url: params[:url])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contest_params
      params.require(:contest).permit(:name, :banner, :url, :startDate, :endDate, :value, :script, :recomendations)
    end
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/views/contests/_form.html.erb
<%= form_for @contest, html: { multipart: true } do |f| %>
  <% if contest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contest.errors.count, "error") %> prohibited this contest from being saved:</h2>

      <ul>
      <% contest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<form>
  <div class="form-group row">  
    <label for="inputEmail3" class="col-sm-2 col-form-label">Nombre*</label>
    <div class="col-sm-10">
      <%= f.text_field(:name, {:class => 'form-control'}) %>
    </div>
  </div>

  <div class="form-group row">  
   <label for="inputEmail3" class="col-sm-2 col-form-label"><em>Banner* </em><br></label>
    <div class="col-sm-10">
      <%= f.file_field :banner %>
    </div>
  </div>

  <div class="form-group row">  
    <label for="inputEmail3" class="col-sm-2 col-form-label"><em>URL*</em><br></label>
    <div class="col-sm-10">
      <%= f.text_field(:url, {:class => 'form-control'}) %>
    </div>
  </div>

  <div class="form-group row">  
   <label for="inputEmail3" class="col-sm-2 col-form-label"><em>Inicio*</em></label>
    <div class="col-sm-10">
     <%= f.date_select :startDate %>
    </div>
  </div>

  <div class="form-group row">  
   <label for="inputEmail3" class="col-sm-2 col-form-label"><em>Fin*</em></label>
    <div class="col-sm-10">
     <%= f.date_select :endDate %>
    </div>
  </div>

  <div class="form-group row">  
   <label for="inputEmail3" class="col-sm-2 col-form-label"><em>Remuneración($)*</em></label>
    <div class="col-sm-10">
     <%= f.text_field(:value, {:class => 'form-control'}) %>
    </div>
  </div>

  <div class="form-group row">  
   <label for="inputEmail3" class="col-sm-2 col-form-label"><em>Guión/Texto*</em></label>
    <div class="col-sm-10">
     <%= f.text_area(:script, {:class => 'form-control'}) %>
    </div>
  </div>

  <div class="form-group row">  
   <label for="inputEmail3" class="col-sm-2 col-form-label"><em>Recomendación*</em></label>
    <div class="col-sm-10">
     <%= f.text_area(:recomendations, {:class => 'form-control'}) %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit("Guardar concurso", {:class => 'btn btn-success btn-lg btn-block'}) %>
  </div>
<% end %>

</div>
</form>

app/views/contests/edit.html.erb
<p></p>
<body class="gray">
   <div class="center2">
       <div class="container-fluid"><br>
         <h1>Editar concurso</h1>

          <%= render 'form', contest: @contest %>

          <%= link_to 'Mostrar', contests_path+'/'+@contest.url %> |
          <%= link_to 'Atrás', contests_path %>
       </div>
    </div>
</body>

app/views/contests/index.html.erb
<% if user_signed_in?%>



<div class="jumbotron">
  <h1 class="display-4">Hola, <%= current_user.email %>!</h1><br>
  <div style= "margin-left: 5em; margin-right: 30em">
  <p class="lead">Encuentra las mejores voces para tus anuncios publicitarios (videos en YouTube, comerciales en TV y radio, etc.), crea y gestiona tus propios concursos que se ajusten a lo que estás buscando.</p></div>
  <hr class="my-4">
  <p class="lead">
    <a class="btn btn-primary btn-lg text-light" href="/contests/new" role="button" >Crear un nuevo concurso</a>
  </p>
</div>
<% end %>


<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-sm">
     <em><h1 style="text-align: center;">Concursos</h1></em>

     <% @contests.sort_by(&:created_at).reverse.each do |contest| %>


 
       <div class="card" style="width: fill;">
          <div><%= image_tag(contest.banner , width: '200 px') %></div>
          <div class="card-body">
            <h5 class="card-title"><td><%= contest.name %></td></h5>
            <p class="card-text"><%= contest.script %></p>
            <%= link_to 'Ir al concurso', 'contests/'+contest.url, :class => "btn btn-primary btn-sm btn-block text-light" %><p></p>
            <% if user_signed_in? %>
              <%= link_to 'Editar', 'contests/'+contest.url+'/edit', :class => "btn btn-primary btn-sm btn-block text-light" %><p></p>
              <%= link_to 'Eliminar', 'contests/'+contest.url, method: :delete, data: { confirm: '¿Está seguro?' }, :class => "btn btn-primary btn-sm btn-block text-light" %><p></p>
            <% end %>
          </div>
       </div><p></p>
      <% end %>
    </div>
  </div>
</div>

app/views/contests/new.html.erb
<p></p>
<body class="gray">
   <div class="center2">
       <div class="container-fluid"><br>
           <em><h1>Nuevo concurso</h1></em><br>

           <%= render 'form', contest: @contest %>
      </div>
   </div>
</body>

app/views/contests/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col">
     <div class="sticky-top">
       
       <%= image_tag(@banner, width: '200 px') do %> 
       <% end %>
       <br>
       <p>
         <h5 class="card-title">Nombre:</h5>
         <h6 class="card-subtitle mb-2 text-muted"><%= @contest.name %></h6>
       </p>
 
       <p>
         <h5 class="card-title">Administrador:</h5>
         <h6 class="card-subtitle mb-2 text-muted"><%= @contest.user.email %></h6>
       </p>
 
       <p>
         <h5 class="card-title">Url:</h5>
         <h6 class="card-subtitle mb-2 text-muted"><%= @contest.url %></h6>
       </p>
 
       <p>
         <h5 class="card-title">Fecha de inicio:</h5>
         <h6 class="card-subtitle mb-2 text-muted"><%= @contest.startDate %></h6>
       </p>
 
       <p>
         <h5 class="card-title">Fecha de finalización:</h5>
         <h6 class="card-subtitle mb-2 text-muted"><%= @contest.endDate %></h6>
       </p>
 
       <p>
         <h5 class="card-title">Remuneración:</h5>
         <h6 class="card-subtitle mb-2 text-muted">$<%= @contest.value %></h6>
       </p>
 
       <p>
         <h5 class="card-title">Guión / Texto:</h5>
         <h6 class="card-subtitle mb-2 text-muted"><%= @contest.script %></h6>
       </p>
 
       <p>
         <h5 class="card-title">Recomendaciones:</h5>
         <h6 class="card-subtitle mb-2 text-muted"><%= @contest.recomendations %></h6>
       </p>



        <%= link_to 'Participa en el concurso', {:controller => "voices", :action => "new", :contest_id => @contest.id}, :class => "btn btn-primary btn-lg" %>
     </div>
   </div>


    <div class="col-sm">
     <p class="lead">
       <%= link_to 'Participa en el concurso', {:controller => "voices", :action => "new", :contest_id => @contest.id}, :class => "btn btn-primary btn-lg btn-block" %>  
     </p>

     <em><h1 class="h1">Voces participantes</h1></em>
        <% @voices.sort_by(&:created_at).reverse.each do |voice| %>
          <div class="card" style="width: fill;">
            <div class="card-body">
              <h5 class="card-title">Nombre: <%= voice.name %></h5>
              <h6 class="card-subtitle mb-2 text-muted">Email: <%= voice.email %></h6>
              <h6 class="card-subtitle mb-2 text-muted">Estado: <%= voice.status.name %></h6>
              <p class="card-text">
                <% if voice.status_id == 2 %>
                  <a href=<%= "http://d2gnw0j9fh1sj8.cloudfront.net/public/assets/voices/"+voice.id.to_s+"/original/"+voice.original_file_file_name.to_s %> download>Audio</a>
                  <%=audio_tag("http://d2gnw0j9fh1sj8.cloudfront.net/public/assets/voices/"+voice.id.to_s+"/convertido/"+voice.converted_file_file_name.to_s, autoplay: false, controls: true)%>
                <% end %>
              </p>
              <% if user_signed_in? %>
                <%= link_to 'Show', voice %>
                <%= link_to 'Edit', edit_voice_path(voice) %>
                <%= link_to 'Destroy', voice, method: :delete, data: { confirm: '¿Estás seguro?' } %>
              <% else %>
              <% end %>
            </div>
          </div> 
          <br>
        <% end %>
    </div>
  </div>
</div>