config/routes.rb
Rails.application.routes.draw do
  get 'send/index'

  resources :voices
  resources :statuses
  resources :contests, param: :url
  get 'home/index'
  devise_for :users
  root 'home#index', as: 'home'
  get  '/contests',   to: 'contests#index'
  get  '/voice',  to: 'voices#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 end

app/models/voice.rb
class Voice < ApplicationRecord
	belongs_to :contest
	belongs_to :status, optional: true
#	after_create :send_mail 
	has_attached_file :original_file,
                  :url  => "http://vocesclouds3.s3.amazonaws.com/",
                  :path => "/public/assets/voices/:id/:style/:basename.:extension", 
				  validate_media_type: false

    validates_attachment_presence :original_file
	validates_attachment_size :original_file, :less_than => 100.megabytes
	validates_attachment_content_type :original_file, :content_type => ['audio/wav',
		'audio/mpeg', 'video/mp4', 'audio/x-wav', 'application/ogg', 'audio/ogg', 
		'video/ogg',
		'audio/x-mpeg', 'audio/mp3', 'audio/x-mp3', 'audio/mpeg3', 'audio/x-mpeg3', 
		'audio/mpg', 'audio/x-mpg', 'audio/x-mpegaudio', 'application/octet-stream',
		'application/mp3', 'application/x-mp3'],
		message: 'El archivo debe ser de formato .mp3, .wav or ogg'

	validates :email,  presence: true
	validates :name,  presence: true
	validates :surname,  presence: true



#	def send_mail

#		
#		MyMailer.send_email(@voice).deliver		
#	end

#	def send_mail
#		#VoiceMailer.convert_confirmation.deliver_later
#	end

end

app/controllers/voices_controller.rb
require 'net/http'

class VoicesController < ApplicationController
  before_action :set_voice, only: [:show, :edit, :update, :destroy]

  # GET /voices
  # GET /voices.json
  def index
    @voices = Voice.all
  end

  # GET /voices/1
  # GET /voices/1.json
  def show
  end

  # GET /voices/new
  def new
    @voice = Voice.new
    @voice.contest_id = Contest.find(params[:contest_id])
  end

  # GET /voices/1/edit
  def edit
  end

  # POST /voices
  # POST /voices.json
  def create
    @voice = Voice.new(voice_params)
    @voice.upload_date = Date.today.to_s
    @voice.status_id = 1
    logger.debug '-----------------------'+@voice.original_file.path
    respond_to do |format|
      if @voice.save
        logger.debug @voice.id
        Aws.use_bundled_cert!
        sqs = Aws::SQS::Client.new(region: 'us-east-2', credentials: Aws::Credentials.new())
        resp = sqs.send_message({queue_url: "https://sqs.us-east-2.amazonaws.com/800983206590/SQSVocesCloud",
                                  message_body: @voice.to_json,
                                  delay_seconds: 1
                                  })
        ConMailer.confirmation(@voice).deliver     
        format.html { redirect_to '/contests/'+@voice.contest.url, notice: 'Voice was successfully added.' }
        format.json { render :show, status: :created, location: @voice }
      else
        format.html { render :new }
        format.json { render json: @voice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /voices/1
  # PATCH/PUT /voices/1.json
  def update
    respond_to do |format|
      if @voice.update(voice_params)
        format.html { redirect_to @voice, notice: 'la voz se actualizó correctamente.' }
        format.json { render :show, status: :ok, location: @voice }
      else
        format.html { render :edit }
        format.json { render json: @voice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voices/1
  # DELETE /voices/1.json
  def destroy
    @voice.destroy
    respond_to do |format|
      format.html { redirect_to voices_url, notice: 'La voz fue eliminada.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voice
      @voice = Voice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def voice_params
      params.require(:voice).permit(:contest_id, :email, :name, :surname, :upload_date, :status_id, :original_file, :converted_file)
    end
end

app/helpers/voices_helper.rb
module VoicesHelper
end

app/views/voices/_form.html.erb
<%= form_for(voice) do |f| %>
  <% if voice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(voice.errors.count, "error") %> prohibited this voice from being saved:</h2>

      <ul>
      <% voice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :contest_id, :value => params[:contest_id] %>
<form>
  <div class="form-group row">  
    <label for="inputEmail3" class="col-sm-2 col-form-label">Email*</label>
    <div class="col-sm-10">
     <%= f.text_field(:email, {:class => 'form-control'}) %><p></p>
    </div>

    <label for="inputEmail3" class="col-sm-2 col-form-label">Nombre</label>
    <div class="col-sm-10">
    <%= f.text_field(:name, {:class => 'form-control'}) %><p></p>
    </div>

    <label for="inputEmail3" class="col-sm-2 col-form-label">Surname</label>
    <div class="col-sm-10">
    <%= f.text_field(:surname, {:class => 'form-control'}) %><p></p>
  </div>

  <label for="inputEmail3" class="col-sm-2 col-form-label">Subir audio</label>
  <div class="col-sm-10">
   <%= f.file_field :original_file %><p></p>
  </div>

  <div class="actions">
    <%= f.submit("Participar", {:class => 'btn btn-success btn-lg btn-block'}) %>
  </div>

  
<% end %>

</div>
</form>

app/views/voices/edit.html.erb
<h1>Editing Voice</h1>

<%= render 'form', voice: @voice %>

<%= link_to 'Show', @voice %> |
<%= link_to 'Back', voices_path %>

app/views/voices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Voices</h1>

<table>
  <thead>
    <tr>
      <th>Contest</th>
      <th>Email</th>
      <th>Name</th>
      <th>Surname</th>
      <th>Upload date</th>
      <th>Status</th>
      <th>Original file</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
    <% @voices.sort_by(&:created_at).reverse.each do |voice| %>
      <tr>
        <td><%= voice.contest.name %></td>
        <td><%= voice.email %></td>
        <td><%= voice.name %></td>
        <td><%= voice.surname %></td>
        <td><%= voice.upload_date %></td>
        <td><%= voice.status.name %></td>
        <td><%= voice.original_file %></td>
        <td><%= link_to 'Show', voice %></td>
        <td><%= link_to 'Edit', edit_voice_path(voice) %></td>
        <td><%= link_to 'Destroy', voice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Voice', new_voice_path %>

app/views/voices/new.html.erb
<p></p>
<body class="gray">
   <div class="center2">
       <div class="container-fluid"><br>

         <h1>Participa en el concurso</h1>
    
         <%= render 'form', voice: @voice %>

     </div>
   </div>
</body>

app/views/voices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Contest:</strong>
  <%= @voice.contest.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @voice.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @voice.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @voice.surname %>
</p>

<p>
  <strong>Upload date:</strong>
  <%= @voice.upload_date %>
</p>

<p>
  <strong>Original file:</strong>
  <%= @voice.original_file %>
</p>

<p>
  <strong>Status:</strong>
  <%= @voice.status %>
</p>

<%= link_to 'Edit', edit_voice_path(@voice) %> |
<%= link_to 'Back', voices_path %>